name: Appointment_App
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast: ^7.0.2
  curved_navigation_bar: ^0.3.3
  percent_indicator: ^2.1.5
  flutter_svg: ^0.18.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/chikitsuck.png
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/icons/
    - assets/images/
    - assets/
