name: Appointment_App
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast: ^7.0.2
  curved_navigation_bar: ^0.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/chikitsuck.png
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
  